build.gradle, src/main/java/it/rate/webapp/dtos/SignupUserInDTO.java, src/main/java/it/rate/webapp/services/UserService.java, src/test/java/it/rate/webapp/services/UserServiceTest.java
=> Rib 24 add validation library to the project and give example

src/main/resources/static/scripts/index.js, src/main/resources/static/styles/index.css, src/main/resources/templates/index.html
- Basic Styling of index page
- Search bar / Interest Links working
- Background color used as placeholder for future images
- Current view for mobile only
- JS former code only commented out for now in case i ~~fuc~~ messed up someone elses code.
- Feel free to make improvements
- Not great , not terrible..
=> RIB-20: Implement-main-page-design

src/main/java/it/rate/webapp/controllers/PlaceController.java, src/main/java/it/rate/webapp/services/PlaceService.java, src/test/java/it/rate/webapp/services/PlaceServiceTest.java
Created tests for place service. 
Why are we returning -1 when no ratings are found? Tests are implemented to check it but I am still not sure why is that happening.
=> Rib 40 create place service tests

src/test/java/it/rate/webapp/controllers/InterestAdminControllerIntegrationTest.java, src/test/java/it/rate/webapp/services/ManageInterestServiceTest.java
- Unit Tests for ManageInterestService
- InterestAdminController's integration tests for accessing secured implemented methods
=> Rib 52 create tests for manage interest service

src/main/java/it/rate/webapp/config/security/SecurityConfig.java, src/main/java/it/rate/webapp/controllers/InterestAdminController.java, src/main/java/it/rate/webapp/controllers/InterestController.java, src/main/java/it/rate/webapp/controllers/MainPageController.java, src/main/java/it/rate/webapp/controllers/PlaceController.java, src/main/java/it/rate/webapp/controllers/api/InterestRestController.java, src/main/java/it/rate/webapp/services/ManageInterestService.java, src/main/java/it/rate/webapp/services/PermissionService.java, src/main/java/it/rate/webapp/services/PlaceService.java, src/main/resources/static/icons/hamburger.svg, src/main/resources/static/icons/search.svg, src/main/resources/static/icons/user.svg, src/main/resources/static/scripts/index.js, src/main/resources/static/styles/index.css, src/main/resources/templates/index.html, src/main/resources/templates/interest.html, src/main/resources/templates/place.html, src/main/resources/templates/usersOfInterest.html, src/test/java/it/rate/webapp/controllers/InterestAdminControllerIntegrationTest.java, src/test/java/it/rate/webapp/controllers/PlaceControllerIntegrationTest.java, src/test/java/it/rate/webapp/services/ManageInterestServiceTest.java
- Readjusted security to permit only specific endpoints and secure all other ones
- Role based access set for all endpoints as per google sheet in RIB-44 (including ADMIN access)
- Refactored endpoints as per google sheet in RIB-44
- Fixed Bugs I was able to spot before refactoring (Hopefully not many more)
- Refactored Tests to match new endpoints, Add new tests, Remove no longer needed tests
- Little visual tweaks on index page
- 2 new static directories for images and icons (svgs)
=> Rib 51 implement changes proposed in rib 44

src/main/resources/static/scripts/index.js, src/main/resources/static/styles/index.css, src/main/resources/templates/main/index.html
- My intereset / Discover New style text --> now as \<h2\>
- See All / Create new Interest text --> now as \<h3\>
- \<body\> now containing Font Montserrat which will be used everywhere unless specified
- Removed interest-name css class and put into interest-title for better readability
=> RIB-68: amend CSS tags

src/main/java/it/rate/webapp/controllers/PlaceController.java, src/main/resources/static/styles/index.css, src/main/resources/templates/place/form.html
=> Rib 65 implement add edit place page

src/main/java/it/rate/webapp/controllers/InterestController.java, src/main/java/it/rate/webapp/dtos/PlaceInfoDTO.java, src/main/java/it/rate/webapp/services/PlaceService.java, src/main/resources/static/scripts/rating.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/page.html, src/main/resources/templates/place/page.html, src/test/java/it/rate/webapp/services/PlaceServiceTest.java
- Implementing styles for interest/page.html
- Adding necessary backend logic in PlaceService and DTO for sending the data to template
- Enhancing rating.js and fixing rating number on frontend to be in line with number stars 
- Implement search bar
- Implement top bar menu with like/dislike button, edit interest, request rating access button - all based on users role
- Implement category filtering
=> Rib 62 implement interest page

src/main/resources/templates/main/index.html
=> RIB-67: add link to create new interest to main page

src/main/resources/templates/interest/form.html, src/main/resources/templates/main/index.html
Extensive and exhausting refactoring of filters.
=> RIB-102-Hide-tag-filters-for-now-and-sort-by-default

src/main/resources/static/scripts/placeSearch.js
- Image loading next to the right places even after using searchbar
- Places in interests now show first added picture in thumbnail, last on on place view
=> Hotfix image loading on interest page

src/main/java/it/rate/webapp/controllers/advice/BadRequestAdvice.java, src/main/java/it/rate/webapp/controllers/advice/InternalErrorAdvice.java, src/main/java/it/rate/webapp/services/InterestService.java
- Add 2 more exceptions to be caught on invalid input
- Add condition to apply Applicant role only if given interest is exclusive therefore preventing user to amend interest id in "Request vote authority" form to a public interest id and creating an invalid record in database
- Internal error email sending commented out as if email sending throws an exception, infinite loop is going to occur.
=> Apply applicant role only for exclusive interest

src/main/java/it/rate/webapp/models/Interest.java, src/main/java/it/rate/webapp/services/InterestService.java, src/test/java/it/rate/webapp/services/InterestServiceTest.java
- Add validation constraints
- Add name to interest builder in tests to pass validation constraint
=> Fix input validation on manage interest

src/main/java/it/rate/webapp/WebappApplication.java, src/main/java/it/rate/webapp/controllers/ImageController.java, src/main/java/it/rate/webapp/dtos/PlaceInfoDTO.java, src/main/java/it/rate/webapp/models/Place.java, src/main/java/it/rate/webapp/services/PlaceService.java, src/main/resources/static/scripts/placeSearch.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/form.html, src/main/resources/templates/interest/page.html, src/main/resources/templates/main/index.html, src/main/resources/templates/place/page.html, src/test/java/it/rate/webapp/services/PlaceServiceTest.java
- adding sorting buttons to interest page
- sorting options are:
1. by distance from nearest place
2. by overall rating from top place
3. by rating of every criterion of given interest from top place (every criterion gets its own button)
- all sorting is being performed in javascript
- adding some more mock data to be able to test sorting
- changing PlaceInfoDTO to contain all criteria
- changing overall behavior of averageRating - when there are no ratings, avgRating is now null
=> Rib 103 add place filters

src/main/resources/static/scripts/interestLike.js, src/main/resources/static/styles/index.css, src/main/resources/templates/fragments.html
- changing like button to outline when interest is not liked, unifying the color for both states
=> Rib 113 change design of like button

src/main/java/it/rate/webapp/config/security/SecurityConfig.java, src/main/java/it/rate/webapp/controllers/ImageController.java, src/main/java/it/rate/webapp/controllers/InterestController.java, src/main/java/it/rate/webapp/controllers/api/ImageRestController.java, src/main/java/it/rate/webapp/dtos/ImageUploadResponseDTO.java, src/main/java/it/rate/webapp/dtos/InterestSuggestionDTO.java, src/main/java/it/rate/webapp/models/Criterion.java, src/main/java/it/rate/webapp/models/Interest.java, src/main/java/it/rate/webapp/services/CreateInterestService.java, src/main/java/it/rate/webapp/services/GoogleImageService.java, src/main/java/it/rate/webapp/services/ImageService.java, src/main/java/it/rate/webapp/services/InterestService.java, src/main/java/it/rate/webapp/services/PermissionService.java, src/main/resources/static/scripts/imageFetcher.js, src/main/resources/static/scripts/index.js, src/main/resources/static/scripts/interestImageUpload.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/form.html, src/main/resources/templates/interest/page.html, src/main/resources/templates/main/index.html, src/test/java/it/rate/webapp/controllers/api/InterestRestControllerTest.java, src/test/java/it/rate/webapp/services/GoogleImageServiceTest.java
- image can be added to newly created interest or when editing old one
- when editing, old image is deleted
- Interest image shows on interest view
- Interest images show on main view
- Favourites on main view are loaded using thymeleaf, all interests are loaded using JS
- All images are loaded when user enters page (no need to load every time user uses searchbar)
- When no image is added to interest, random image is fetched
- When user succesfully uploads image, button changes to "Change image"
- Right now if user changes his mind and want to upload different image while creating new interest, we keep old image on google disk (to be fixed)
=> Rib 93 upload main image for interest page

build.gradle, docker/docker-compose.yml, src/main/resources/application-dev.properties, src/main/resources/application-production.properties, src/test/resources/application-test.properties
- For now still no flyway
- Separate upload directory for dev / production use on gDrive
=> Rib 95 add proper database

src/main/resources/static/scripts/index.js, src/main/resources/templates/fragments.html, src/main/resources/templates/interest/page.html, src/main/resources/templates/main/index.html
- implementing https://splidejs.com/ into main page to have some kind of carousel
=> add splide carousel prototype

src/main/resources/static/scripts/index.js
=> RIB-136: changes to the carousel

src/main/resources/templates/main/index.html
=> RIB-141: login to see your interests and no interests changed

src/main/resources/templates/interest/form.html
=> RIB-137: make interest description required

src/main/java/it/rate/webapp/controllers/PlaceController.java, src/main/java/it/rate/webapp/controllers/api/PlaceRestController.java, src/main/resources/static/scripts/rating.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/map.html, src/main/resources/templates/interest/page.html, src/main/resources/templates/place/page.html
- when user hits RATE button in place page, data is sent to REST endpoint instead of reloading whole page
- fix javascript error of like not being available when no user is logged in or user is creator
- minor tweaks in css of place cards in interest page
- move id="uppy" div outside of rating form to not mess with the rating
=> Rib 114 change rating in place to call rest api endpoint

src/main/resources/static/styles/index.css, src/main/resources/templates/main/index.html
- Reworked like design
- Long titles no longer overflow
=> Rib 139 change my interests design

src/main/java/it/rate/webapp/WebappApplication.java, src/main/java/it/rate/webapp/models/Category.java, src/main/java/it/rate/webapp/models/Interest.java, src/main/java/it/rate/webapp/repositories/CategoryRepository.java, src/main/resources/application-dev.properties
~~Be aware that in the commit, preload data was set to true and ddl to create-drop.
amend as necessary on your end after merge~~
=> RIB-127 Create category model and relationship

build.gradle, src/main/java/it/rate/webapp/WebappApplication.java, src/main/java/it/rate/webapp/controllers/ImageController.java, src/main/java/it/rate/webapp/controllers/api/ImageRestController.java, src/main/java/it/rate/webapp/services/GoogleImageService.java, src/main/java/it/rate/webapp/services/ImageService.java, src/main/java/it/rate/webapp/utils/ImageEditor.java, src/main/resources/application-dev.properties, src/main/resources/application.properties, src/main/resources/static/scripts/imageUpload.js, src/test/java/it/rate/webapp/services/GoogleImageServiceTest.java
- File upload cannot exceed 5 MB. 
- When user uploads image bigger than 1MB, it will be com compressed accordingally. 
- Added image cache
=> Rib 76 compressed thumbnails of user uploaded images are created to decrease website size

src/main/resources/application-dev.properties, src/main/resources/static/scripts/interestImageUpload.js, src/main/resources/static/styles/index.css, src/main/resources/templates/fragments.html, src/main/resources/templates/place/page.html
- added fotorama library
- images in places now appear in gallery style view (if more than one is present)
- beneath them are showed thumbnails
- If no picture is present, than no picture is shown. 
- Pictures can be shown in fullscreen when clicked
- Library customizable, can add photo captions in the future for example
=>  RIB-145-Allow-for-multiple-images-in-place-view

src/main/resources/static/styles/index.css, src/main/resources/templates/error/page.html, src/main/resources/templates/fragments.html, src/main/resources/templates/interest/form.html, src/main/resources/templates/interest/invite.html, src/main/resources/templates/interest/map.html, src/main/resources/templates/interest/page.html, src/main/resources/templates/interest/seeAll.html, src/main/resources/templates/interest/users.html, src/main/resources/templates/main/index.html, src/main/resources/templates/place/form.html, src/main/resources/templates/place/page.html, src/main/resources/templates/user/loginForm.html, src/main/resources/templates/user/signupForm.html
- creating a simple page footer for now with dummy texts
- adding the footer to all pages
- moving the logo on sign-in/register page into the form for hopefully better design
=> Rib 125 create footer in every page use fragments

src/main/java/it/rate/webapp/config/ThymeMath.java, src/main/resources/static/scripts/rating.js, src/main/resources/templates/place/page.html
- when rating a place, the number of stars can be set by dragging on the touch screen
- adding ability to delete rating by dragging all the way to the left (when no stars are filled, empty rating is sent and if current rating exists, it is deleted)
- fix issue with incorrect rounding of average score in Thymeleaf (score of 4,25 was rounded down to 4,2 and that led to an inconsistency with displaying of ratings)
=> Rib 144 add the ability to change the number of rating stars by dragging on the touchscreen

src/main/resources/static/scripts/checkboxesSplide.js, src/main/resources/static/scripts/index.js, src/main/resources/static/scripts/indexSplide.js, src/main/resources/static/scripts/placeSearch.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/page.html, src/main/resources/templates/main/index.html
- sorting places by criteria works properly with searchbar (same way as filtering and searching interests)
- sorting places by distance is only available if the user has allowed access to their location, otherwise the button is missing
- adding splide to sort buttons - same design as filtering interests by category
=> Rib 149 fix sorting places to work properly with search bar

src/main/java/it/rate/webapp/config/security/SecurityConfig.java, src/main/java/it/rate/webapp/controllers/FooterController.java, src/main/java/it/rate/webapp/controllers/advice/InternalErrorAdvice.java, src/main/java/it/rate/webapp/controllers/api/EmailController.java, src/main/java/it/rate/webapp/dtos/EmailMessageDTO.java, src/main/java/it/rate/webapp/services/EmailService.java, src/main/java/it/rate/webapp/services/EmailServiceImpl.java, src/main/resources/application.properties, src/main/resources/static/scripts/contactUs.js, src/main/resources/static/styles/index.css, src/main/resources/templates/footer/about.html, src/main/resources/templates/footer/contact.html, src/main/resources/templates/footer/developers.html, src/main/resources/templates/footer/terms.html, src/main/resources/templates/fragments.html
- Added placeholder pages for footer links
- Fully working contact form
- Email is sent from our centrum address to gmail, message contains user's or anonymous person's email address and their message
=> Footer pages prototypes

src/main/resources/static/scripts/interestMap.js, src/main/resources/static/scripts/placeFormMap.js, src/main/resources/static/scripts/placeMap.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/map.html, src/main/resources/templates/place/form.html, src/main/resources/templates/place/page.html
- using https://nominatim.openstreetmap.org/ free APIs for geocoding and reverse geocoding
- the address is filled in automatically after placing the pin on the map
- the place can be found by address, the pin will then be placed on the map automatically
- message is displayed if the given address is too unspecific or no results were found
- adding location accuracy information when getting the current location using the button
- links to places in Google Maps are displayed in popups on the interest map and places maps instead of coordinates
=> Rib 134 find a way how to automatically get address from coordinates when creating place

src/main/java/it/rate/webapp/controllers/InterestAdminController.java, src/main/java/it/rate/webapp/enums/InviteBy.java, src/main/java/it/rate/webapp/services/EmailService.java, src/main/java/it/rate/webapp/services/EmailServiceImpl.java, src/main/java/it/rate/webapp/services/ManageInterestService.java, src/main/resources/static/scripts/interestUsers.js, src/main/resources/templates/interest/invite.html, src/test/java/it/rate/webapp/services/ManageInterestServiceTest.java
- Change inviteBy parameter to enum
- Error message added for invitation if target user is already a member
- On successful application, target user receives email notification with a link to the interest he has been invited to
_note : Link is currently not clickable in email, due to usage of SimpleMailMessage. If we want a clickable link and/or posssible style this email, we need to use a different MailMessage implementation_
=> RIB-75 Figure out how to notify user when it has been invited to an interest

src/main/java/it/rate/webapp/config/security/SecurityConfig.java, src/main/java/it/rate/webapp/controllers/FooterController.java, src/main/resources/static/styles/index.css, src/main/resources/templates/footer/legal/privacyPolicy.html, src/main/resources/templates/footer/legal/termsAndConditions.html, src/main/resources/templates/fragments.html, src/main/resources/templates/user/signupForm.html
If anyone knows anything about the law please check the documents
I couldn't fit everything into the footer so I removed developers link - was there a reason to have developers and about split into two or could we merge that into one page?
I also increased the padding on the footer a little bit and added underline on hover to the links.
=> Rib 169 check if some legal stuff is required in the footer

src/main/resources/static/styles/index.css
=> RIB-176: Fix small screen view for square images

src/main/resources/static/scripts/rating.js, src/main/resources/static/styles/index.css, src/main/resources/templates/place/page.html
**RIB-87: Removing rating**
- Added an extra star, half completely hidden, half just invisible but clickable.
- Added pointer cursor so it's easy to see.
- Not great, not terrible. 😅
=> RIB-87: user can remove rating of a place

src/main/resources/static/scripts/userBioEdit.js, src/main/resources/static/styles/index.css, src/main/resources/templates/user/loginForm.html
- fixed signup CSS for small screens
- login placeholder correctly says email and not username
- bio javascript no longer saves default text as bio if no text is entered
=> Minor visual bug fixes

src/main/resources/static/scripts/index.js, src/main/resources/static/scripts/placeSearch.js, src/main/resources/static/styles/index.css, src/main/resources/templates/interest/page.html, src/main/resources/templates/main/index.html
- added spinner to index view and interest view
- spinner is displayed before fetch for suggestions is completed, afterwards changes display to none
- If you want to test spinner, add     await new Promise(resolve => setTimeout(resolve, 5000)); to DOMContentLoaded event listener before try/catch block in index.html
- 
- Spinner is moving smoother, gif capturer limits me to 10 FPS
=> Rib 185 add loading icon when loading interests and places

build.gradle, src/main/java/it/rate/webapp/controllers/BaseThymeleafController.java, src/main/java/it/rate/webapp/controllers/FooterController.java, src/main/java/it/rate/webapp/controllers/InterestAdminController.java, src/main/java/it/rate/webapp/controllers/InterestController.java, src/main/java/it/rate/webapp/controllers/MainPageController.java, src/main/java/it/rate/webapp/controllers/MapController.java, src/main/java/it/rate/webapp/controllers/PlaceController.java, src/main/java/it/rate/webapp/controllers/UserController.java, src/main/resources/static/styles/index.css, src/main/resources/templates/fragments.html
- version is displayed in footer
- CSS for interest image on user page adjusted as well
Edits:
- refactored controllers to minimize duplicate code
- made version only visible in the HTML code
=> Rib 173 users should be able to see the project version

src/main/resources/static/styles/index.css
- All green text color is the same
- Text of categories in interest form are no longer selectable
- Sort/filter colors applied to toggle as well
=> RIB-187-Make-colors-consitent

.github/workflows/deployment.yml
- Need to set up GH Actions secrets before running the workflow
=> RIB-99: Add auto deployment on push to master branch

src/main/resources/static/scripts/placeSearch.js
Fix sorting places to sort NaN values correctly
=> Sorting places hotfix
